{% set name = "pygls" %}
{% set version = "0.10.3" %}

package:
  name: pygls
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 522c1068dd38c4945925ca742daba6aff5621168e0e5ddd954813e8b957ca831
  - folder: src
    url: https://github.com/openlawlibrary/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: b3262f6abf021eb43fe590aa39aba481d45be4f15d528d51b0866b200cdae173

build:
  noarch: python
  number: 1
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - pydantic >=1.7,<1.9
    - python >=3.6
    - typeguard >=2.10.0,<3

test:
  source_files:
    - src/tests
  requires:
    - mock
    - pip
    - pytest
    - pytest-asyncio
    - pytest-cov
    - pytest-timeout
  imports:
    - pygls
  commands:
    - python -m pip check
    - pip list | pip list | grep 'pygls\s+{{ version.replace('.', '\.') }}' # [unix]
    # TODO: remove skip https://github.com/openlawlibrary/pygls/issues/165
    - cd src/tests
    - python -m pytest -vv --timeout 30 --durations 10 -k "not tcp_connection_lost" --cov pygls --cov-branch --cov-fail-under 86 --cov-report term-missing:skip-covered --no-cov-on-fail

about:
  home: https://pygls.readthedocs.io
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - dist/LICENSE.txt
    - dist/ThirdPartyNotices.txt
  summary: a pythonic generic language server (pronounced like "pie glass").
  description: |
    pygls (pronounced like "pie glass") is a pythonic generic implementation of
    the Language Server Protocol for use as a foundation for writing language
    servers using Python (e.g. Python, XML, etc.). It allows you to write your
    own language server in just a few lines of code.
  dev_url: https://github.com/openlawlibrary/pygls
  doc_url: https://pygls.readthedocs.io
  doc_source_url: https://github.com/openlawlibrary/pygls/tree/master/docs/source

extra:
  recipe-maintainers:
    - bollwyvl
