{% set name = "pygls" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: c21c942415457315f316c0b6c19d4c743fd2974d457e02a85472154c8f1b6399
  - folder: src
    url: https://github.com/openlawlibrary/{{ name }}/archive/v{{ version }}.tar.gz 
    sha256: 78b27edd4e2f6e5bed84a6c2119e0d19e56824bd1839e293069d763956be65e0

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  source_files:
    - src/tests
  requires:
    - mock
    - pip
    - pytest
    - pytest-asyncio
  imports:
    - pygls
  commands:
    - python -m pip check
    - cd src && python -m pytest

about:
  home: https://pygls.readthedocs.io
  license: Apache-2.0
  license_family: APACHE
  license_file: 
    - dist/LICENSE.txt
    - dist/ThirdPartyNotices.txt
  summary: a pythonic generic language server (pronounced like "pie glass").
  description: |
    pygls (pronounced like "pie glass") is a pythonic generic implementation of
    the Language Server Protocol for use as a foundation for writing language
    servers using Python (e.g. Python, XML, etc.). It allows you to write your
    own language server in just a few lines of code.
  dev_url: https://github.com/openlawlibrary/pygls
  doc_url: https://pygls.readthedocs.io
  doc_source_url: https://github.com/openlawlibrary/pygls/tree/master/docs/source

extra:
  recipe-maintainers:
    - bollwyvl
