{% set name = "pygls" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c21c942415457315f316c0b6c19d4c743fd2974d457e02a85472154c8f1b6399

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  source_files:
    - tests
  requires:
    - mock
    - pytest
    - pytest-asyncio
  imports:
    - pygls
  commands:
    - python -m pytest

about:
  home: https://pygls.readthedocs.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: a pythonic generic language server
  description: |
    pygls (pronounced like "pie glass") is a pythonic generic implementation of
    the Language Server Protocol for use as a foundation for writing language
    servers using Python (e.g. Python, XML, etc.). It allows you to write your
    own language server in just a few lines of code.
  dev_url: https://github.com/openlawlibrary/pygls
  doc_url: https://pygls.readthedocs.io
  doc_source_url: https://github.com/openlawlibrary/pygls/tree/master/docs/source

extra:
  recipe-maintainers:
    - bollwyvl
