{% set name = "pygls" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 5b50a1931613f36af446b16c644a85b52ceb2beceb09bddd05f9ce054f13e9ab
  - folder: src
    url: https://github.com/openlawlibrary/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: efed13eb7fed2053913b73b73f88165e81359fe5b4f7f4741077836bd7ad71ee

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - psutil >=5
    - pydantic >=1.7,<1.9
    - python >=3.6
    - typeguard >=2.10.0,<3

test:
  source_files:
    - src/tests
  requires:
    - mock
    - pip
    - pytest
    - pytest-asyncio
  imports:
    - pygls
  commands:
    - python -m pip check
    - cd src && python -m pytest

about:
  home: https://pygls.readthedocs.io
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - dist/LICENSE.txt
    - dist/ThirdPartyNotices.txt
  summary: a pythonic generic language server (pronounced like "pie glass").
  description: |
    pygls (pronounced like "pie glass") is a pythonic generic implementation of
    the Language Server Protocol for use as a foundation for writing language
    servers using Python (e.g. Python, XML, etc.). It allows you to write your
    own language server in just a few lines of code.
  dev_url: https://github.com/openlawlibrary/pygls
  doc_url: https://pygls.readthedocs.io
  doc_source_url: https://github.com/openlawlibrary/pygls/tree/master/docs/source

extra:
  recipe-maintainers:
    - bollwyvl
